# Generated by Django 2.2.3 on 2019-08-05 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0002_userrelation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='userrelation',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='createdat',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userrelation',
            old_name='createdat',
            new_name='created_at',
        ),
    ]
