# Generated by Django 2.2.3 on 2019-08-06 08:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitterapp', '0005_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tweetlike',
            unique_together={('tweet', 'owner')},
        ),
    ]
